import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1774599997645 implements MigrationInterface {
    name = 'InitSchema1774599997645'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`test_executions\` (\`id\` varchar(36) NOT NULL, \`projectId\` varchar(255) NULL, \`taskId\` varchar(255) NOT NULL, \`environmentId\` varchar(255) NULL, \`scriptId\` varchar(255) NULL, \`caseId\` varchar(255) NULL, \`executionNo\` varchar(255) NOT NULL, \`status\` enum ('pending', 'running', 'passed', 'failed', 'skipped') NOT NULL DEFAULT 'pending', \`scriptName\` varchar(255) NULL, \`requestUrl\` varchar(255) NULL, \`requestMethod\` varchar(255) NULL, \`requestHeaders\` json NULL, \`requestBody\` json NULL, \`responseStatus\` int NULL, \`responseBody\` json NULL, \`errorMessage\` text NULL, \`errorStack\` text NULL, \`errorType\` enum ('environment', 'script', 'assertion', 'data', 'unknown') NULL, \`durationMs\` int NOT NULL DEFAULT '0', \`startedAt\` datetime NULL, \`finishedAt\` datetime NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_690f469801eedfea23a8368a51\` (\`executionNo\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` varchar(36) NOT NULL, \`username\` varchar(255) NOT NULL, \`password\` varchar(255) NOT NULL, \`realName\` varchar(255) NOT NULL, \`email\` varchar(255) NOT NULL, \`phone\` varchar(255) NULL, \`role\` enum ('admin', 'tester', 'developer', 'viewer') NOT NULL DEFAULT 'tester', \`status\` enum ('active', 'inactive', 'disabled') NOT NULL DEFAULT 'active', \`avatar\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`lastLoginAt\` datetime NULL, UNIQUE INDEX \`IDX_fe0bb3f6520ee0469504521e71\` (\`username\`), UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`test_scripts\` (\`id\` varchar(36) NOT NULL, \`projectId\` varchar(255) NULL, \`caseId\` varchar(255) NULL, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`type\` enum ('interface', 'ui', 'performance', 'security') NOT NULL DEFAULT 'interface', \`language\` enum ('python', 'java', 'javascript', 'typescript') NOT NULL DEFAULT 'python', \`executionMode\` enum ('lite', 'python') NOT NULL DEFAULT 'lite', \`scriptContent\` text NOT NULL, \`module\` varchar(255) NULL, \`status\` enum ('valid', 'invalid', 'need_optimize') NOT NULL DEFAULT 'valid', \`source\` enum ('ai_generated', 'manual', 'imported') NOT NULL DEFAULT 'manual', \`framework\` varchar(255) NULL, \`frameworkVersion\` varchar(255) NULL, \`tags\` varchar(255) NULL, \`remarks\` varchar(255) NULL, \`isGlobal\` tinyint NOT NULL DEFAULT 0, \`createdBy\` varchar(255) NOT NULL, \`updatedBy\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`creatorId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`test_tasks\` (\`id\` varchar(36) NOT NULL, \`projectId\` varchar(255) NULL, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`type\` enum ('interface_test', 'ui_test', 'performance_test', 'security_test', 'regression_test') NOT NULL DEFAULT 'interface_test', \`status\` enum ('pending', 'running', 'completed', 'failed', 'cancelled') NOT NULL DEFAULT 'pending', \`priority\` enum ('high', 'medium', 'low') NOT NULL DEFAULT 'medium', \`executeType\` enum ('immediate', 'scheduled') NOT NULL DEFAULT 'immediate', \`executeEnvironments\` text NULL, \`scriptIds\` text NULL, \`environmentId\` varchar(255) NULL, \`scheduledTime\` datetime NULL, \`startTime\` datetime NULL, \`endTime\` datetime NULL, \`totalCases\` int NOT NULL DEFAULT '0', \`passedCases\` int NOT NULL DEFAULT '0', \`failedCases\` int NOT NULL DEFAULT '0', \`blockedCases\` int NOT NULL DEFAULT '0', \`skippedCases\` int NOT NULL DEFAULT '0', \`passRate\` decimal(5,2) NOT NULL DEFAULT '0.00', \`progress\` varchar(255) NULL, \`remarks\` text NULL, \`createdBy\` varchar(255) NOT NULL, \`triggerType\` varchar(255) NULL, \`triggerUrl\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`creatorId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`test_data\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`type\` enum ('static', 'dynamic', 'mock') NOT NULL DEFAULT 'static', \`module\` varchar(255) NULL, \`dataContent\` text NOT NULL, \`dataSchema\` varchar(255) NULL, \`status\` enum ('active', 'inactive', 'expired') NOT NULL DEFAULT 'active', \`isSensitive\` tinyint NOT NULL DEFAULT 0, \`sensitiveFields\` varchar(255) NULL, \`tags\` varchar(255) NULL, \`isReusable\` tinyint NOT NULL DEFAULT 0, \`expiresAt\` datetime NULL, \`createdBy\` varchar(255) NOT NULL, \`updatedBy\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`creatorId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`projects\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`code\` varchar(255) NOT NULL, \`businessLine\` varchar(255) NULL, \`ownerId\` varchar(255) NULL, \`description\` text NULL, \`status\` enum ('active', 'inactive', 'archived') NOT NULL DEFAULT 'active', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_2187088ab5ef2a918473cb9900\` (\`name\`), UNIQUE INDEX \`IDX_d95a87318392465ab663a32cc4\` (\`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`test_reports\` (\`id\` varchar(36) NOT NULL, \`projectId\` varchar(255) NULL, \`title\` varchar(255) NOT NULL, \`description\` text NULL, \`type\` enum ('task_report', 'module_report', 'full_report') NOT NULL DEFAULT 'task_report', \`relatedTaskId\` varchar(255) NULL, \`relatedModule\` varchar(255) NULL, \`totalCases\` int NOT NULL DEFAULT '0', \`passedCases\` int NOT NULL DEFAULT '0', \`failedCases\` int NOT NULL DEFAULT '0', \`blockedCases\` int NOT NULL DEFAULT '0', \`skippedCases\` int NOT NULL DEFAULT '0', \`passRate\` decimal(5,2) NOT NULL DEFAULT '0.00', \`totalDefects\` int NOT NULL DEFAULT '0', \`openDefects\` int NOT NULL DEFAULT '0', \`criticalDefects\` int NOT NULL DEFAULT '0', \`majorDefects\` int NOT NULL DEFAULT '0', \`minorDefects\` int NOT NULL DEFAULT '0', \`moduleSummary\` json NULL, \`defectDistribution\` json NULL, \`aiAnalysis\` text NULL, \`aiSuggestions\` text NULL, \`summary\` varchar(255) NULL, \`conclusion\` varchar(255) NULL, \`isAutoGenerated\` tinyint NOT NULL DEFAULT 0, \`createdBy\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`creatorId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`test_cases\` (\`id\` varchar(36) NOT NULL, \`projectId\` varchar(255) NULL, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`preconditions\` text NOT NULL, \`testSteps\` text NOT NULL, \`expectedResult\` text NOT NULL, \`module\` varchar(255) NULL, \`subModule\` varchar(255) NULL, \`type\` enum ('functional', 'interface', 'ui', 'performance', 'security') NOT NULL DEFAULT 'functional', \`priority\` enum ('high', 'medium', 'low') NOT NULL DEFAULT 'medium', \`status\` enum ('draft', 'valid', 'invalid', 'obsolete') NOT NULL DEFAULT 'draft', \`source\` enum ('ai_generated', 'manual', 'imported') NOT NULL DEFAULT 'manual', \`isCoreCase\` tinyint NOT NULL DEFAULT 0, \`tags\` varchar(255) NULL, \`remarks\` varchar(255) NULL, \`createdBy\` varchar(255) NOT NULL, \`updatedBy\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`creatorId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`defects\` (\`id\` varchar(36) NOT NULL, \`projectId\` varchar(255) NULL, \`title\` varchar(255) NOT NULL, \`description\` text NULL, \`type\` enum ('functional', 'ui', 'performance', 'security', 'data', 'configuration') NOT NULL DEFAULT 'functional', \`severity\` enum ('blocker', 'critical', 'major', 'minor', 'trivial') NOT NULL DEFAULT 'minor', \`status\` enum ('open', 'in_progress', 'resolved', 'closed', 'reopened') NOT NULL DEFAULT 'open', \`source\` enum ('ai_detected', 'manual_reported', 'imported') NOT NULL DEFAULT 'manual_reported', \`module\` varchar(255) NULL, \`subModule\` varchar(255) NULL, \`relatedCaseId\` varchar(255) NULL, \`relatedScriptId\` varchar(255) NULL, \`relatedTaskId\` varchar(255) NULL, \`environment\` varchar(255) NULL, \`stepsToReproduce\` varchar(255) NULL, \`actualResult\` varchar(255) NULL, \`expectedResult\` varchar(255) NULL, \`screenshots\` varchar(255) NULL, \`logs\` varchar(255) NULL, \`rootCauseAnalysis\` varchar(255) NULL, \`aiSuggestion\` varchar(255) NULL, \`jiraKey\` varchar(255) NULL, \`assigneeId\` varchar(255) NULL, \`reporterId\` varchar(255) NOT NULL, \`resolvedBy\` varchar(255) NULL, \`resolvedAt\` datetime NULL, \`closedBy\` varchar(255) NULL, \`closedAt\` datetime NULL, \`reopenCount\` int NOT NULL DEFAULT '0', \`remarks\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`resolverId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`environments\` (\`id\` varchar(36) NOT NULL, \`projectId\` varchar(255) NULL, \`name\` varchar(255) NOT NULL, \`type\` enum ('test', 'pre_production', 'production', 'development') NOT NULL, \`baseUrl\` varchar(255) NOT NULL, \`description\` varchar(255) NULL, \`variables\` json NULL, \`headers\` json NULL, \`authConfig\` json NULL, \`status\` enum ('available', 'unavailable', 'maintenance') NOT NULL DEFAULT 'available', \`healthScore\` decimal(5,2) NOT NULL DEFAULT '100.00', \`lastHealthCheck\` datetime NULL, \`isDefault\` tinyint NOT NULL DEFAULT 0, \`remarks\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`test_scripts\` ADD CONSTRAINT \`FK_babd86878ee397c5f5b5d497b82\` FOREIGN KEY (\`creatorId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test_tasks\` ADD CONSTRAINT \`FK_e3077abd510d5e12d0a225fbe86\` FOREIGN KEY (\`creatorId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test_data\` ADD CONSTRAINT \`FK_61a08ac05ef009a5a004298edf5\` FOREIGN KEY (\`creatorId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test_reports\` ADD CONSTRAINT \`FK_01a01f8056481b3d8d8fe682736\` FOREIGN KEY (\`creatorId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`test_cases\` ADD CONSTRAINT \`FK_229862903a144855fd7b62aaae9\` FOREIGN KEY (\`creatorId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`defects\` ADD CONSTRAINT \`FK_16a8b2b6965e9faa7d4dd6b50cf\` FOREIGN KEY (\`assigneeId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`defects\` ADD CONSTRAINT \`FK_b9c89ac1e6a3f984c43996348f7\` FOREIGN KEY (\`reporterId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`defects\` ADD CONSTRAINT \`FK_3d72015f278fb8070826da7a6f5\` FOREIGN KEY (\`resolverId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`defects\` DROP FOREIGN KEY \`FK_3d72015f278fb8070826da7a6f5\``);
        await queryRunner.query(`ALTER TABLE \`defects\` DROP FOREIGN KEY \`FK_b9c89ac1e6a3f984c43996348f7\``);
        await queryRunner.query(`ALTER TABLE \`defects\` DROP FOREIGN KEY \`FK_16a8b2b6965e9faa7d4dd6b50cf\``);
        await queryRunner.query(`ALTER TABLE \`test_cases\` DROP FOREIGN KEY \`FK_229862903a144855fd7b62aaae9\``);
        await queryRunner.query(`ALTER TABLE \`test_reports\` DROP FOREIGN KEY \`FK_01a01f8056481b3d8d8fe682736\``);
        await queryRunner.query(`ALTER TABLE \`test_data\` DROP FOREIGN KEY \`FK_61a08ac05ef009a5a004298edf5\``);
        await queryRunner.query(`ALTER TABLE \`test_tasks\` DROP FOREIGN KEY \`FK_e3077abd510d5e12d0a225fbe86\``);
        await queryRunner.query(`ALTER TABLE \`test_scripts\` DROP FOREIGN KEY \`FK_babd86878ee397c5f5b5d497b82\``);
        await queryRunner.query(`DROP TABLE \`environments\``);
        await queryRunner.query(`DROP TABLE \`defects\``);
        await queryRunner.query(`DROP TABLE \`test_cases\``);
        await queryRunner.query(`DROP TABLE \`test_reports\``);
        await queryRunner.query(`DROP INDEX \`IDX_d95a87318392465ab663a32cc4\` ON \`projects\``);
        await queryRunner.query(`DROP INDEX \`IDX_2187088ab5ef2a918473cb9900\` ON \`projects\``);
        await queryRunner.query(`DROP TABLE \`projects\``);
        await queryRunner.query(`DROP TABLE \`test_data\``);
        await queryRunner.query(`DROP TABLE \`test_tasks\``);
        await queryRunner.query(`DROP TABLE \`test_scripts\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_fe0bb3f6520ee0469504521e71\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_690f469801eedfea23a8368a51\` ON \`test_executions\``);
        await queryRunner.query(`DROP TABLE \`test_executions\``);
    }

}
