import { Entity, Column, PrimaryGeneratedColumn, CreateDateColumn, UpdateDateColumn, ManyToOne } from 'typeorm';
import { User } from '../../user/entities/user.entity';

export enum ReportType {
  TASK_REPORT = 'task_report',
  MODULE_REPORT = 'module_report',
  FULL_REPORT = 'full_report',
}

@Entity('test_reports')
export class TestReport {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ nullable: true })
  projectId: string;

  @Column()
  title: string;

  @Column({ type: 'text', nullable: true })
  description: string;

  @Column({ type: 'enum', enum: ReportType, default: ReportType.TASK_REPORT })
  type: ReportType;

  @Column({ nullable: true })
  relatedTaskId: string;

  @Column({ nullable: true })
  relatedModule: string;

  @Column({ type: 'int', default: 0 })
  totalCases: number;

  @Column({ type: 'int', default: 0 })
  passedCases: number;

  @Column({ type: 'int', default: 0 })
  failedCases: number;

  @Column({ type: 'int', default: 0 })
  blockedCases: number;

  @Column({ type: 'int', default: 0 })
  skippedCases: number;

  @Column({ type: 'decimal', precision: 5, scale: 2, default: 0 })
  passRate: number;

  @Column({ type: 'int', default: 0 })
  totalDefects: number;

  @Column({ type: 'int', default: 0 })
  openDefects: number;

  @Column({ type: 'int', default: 0 })
  criticalDefects: number;

  @Column({ type: 'int', default: 0 })
  majorDefects: number;

  @Column({ type: 'int', default: 0 })
  minorDefects: number;

  @Column({ type: 'json', nullable: true })
  moduleSummary: Record<string, any>;

  @Column({ type: 'json', nullable: true })
  defectDistribution: Record<string, any>;

  @Column({ type: 'text', nullable: true })
  aiAnalysis: string;

  @Column({ type: 'text', nullable: true })
  aiSuggestions: string;

  @Column({ nullable: true })
  summary: string;

  @Column({ nullable: true })
  conclusion: string;

  @Column({ default: false })
  isAutoGenerated: boolean;

  @Column()
  createdBy: string;

  @ManyToOne(() => User)
  creator: User;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}
